resolver: lts-14.11

packages:
  - .
  - ../numhask/numhask
  - ../numhask/numhask-prelude
  - ../numhask/numhask-array
  - ../numhask/numhask-space
  - ../numhask/numhask-hedgehog
  #- ../perf/perf
  #- ../perf/perf-analysis
  #- ../perf/perf-criterion

extra-deps:
  - git: https://github.com/DataHaskell/dh-core.git
    commit: 545c4b974dd35d971dc400836878c15e1c41ee07
    subdirs: 
    - dense-linear-algebra
  - dimensions-1.0.1.1
  #- perf-0.4.1.0
  #- perf-analysis-0.0.1.1
  - rdtsc-1.3.0.1
  - git: https://github.com/tonyday567/readme-lhs.git
    commit: a48c5414051f9833b84ec5a20108a0b641b21a10
  #- git: https://github.com/tonyday567/numhask.git
  #  commit: 91df824544709bbec7e5cc7e437897eb551a5a1a
  #  subdirs:
  #    - numhask
  #    - numhask-prelude
  #    - numhask-space
  #    - numhask-hedgehog
  - git: https://github.com/tonyday567/perf.git
    commit: 807a1cdee8847eed57d162f723f384c3b69c95f8
    subdirs:
      - perf
      - perf-analysis
      - perf-criterion
  # - numhask-0.3.0.0
  # - numhask-array-0.3
  # - numhask-prelude-0.3.1
  # - numhask-space-0.1.1
  # - numhask-hedgehog-0.3
