resolver: nightly-2020-11-19

packages:
  - .

extra-deps:
  - numhask-0.7.0.0
  - protolude-0.3.0
  - random-1.2.0
  - splitmix-0.1.0.3
  - numhask-space-0.7.0.0
  - numhask-array-0.8.0
  - perf-0.7.0
  - formatn-0.0.1

  # perf
  - rdtsc-1.3.0.1

  - git: https://github.com/tonyday567/numhask-massive.git
    commit: 5a2897511f0bffd13277283bc568c712eb3d95d9
  - massiv-0.5.6.0

  - git: https://github.com/tonyday567/numhask-hmatrix.git
    commit: 1976236c92d699f9d6c6e7a8530236b8637322fb

allow-newer: true
