resolver: lts-14.13

packages:
  - .

extra-deps:
  - git: https://github.com/DataHaskell/dh-core.git
    commit: 545c4b974dd35d971dc400836878c15e1c41ee07
    subdirs: 
    - dense-linear-algebra
  - rdtsc-1.3.0.1
  - readme-lhs-0.2.2
  - numhask-space-0.3.0
  - git: https://github.com/tonyday567/numhask-array.git
    commit: 817c3ecdb39e5b808717667686ef870890ef3d9c
  - git: https://github.com/tonyday567/numhask.git
    commit: c941cdc533dd220cceb14f4835941e3a89ae3955
    subdirs:
      - numhask
      - numhask-prelude
      - numhask-hedgehog
  - git: https://github.com/tonyday567/perf.git
    commit: df35c2c6f3e5f4cee0f7fb9368f16969cc2423f8
    subdirs:
      - perf
      - perf-analysis
      - perf-criterion
