resolver: nightly-2020-06-25

packages:
  - .
  - ../numhask-array

extra-deps:
  - numhask-0.6.0.2
  # - numhask-array-0.7.0

  # perf pack
  - perf-0.7.0
  - rdtsc-1.3.0.1
  - readme-lhs-0.7.0
  - pandoc-2.10
  - hslua-1.1.2
  - jira-wiki-markup-1.3.2

allow-newer: true
