resolver: lts-14.13

packages:
  - .

extra-deps:
  - rdtsc-1.3.0.1
  - readme-lhs-0.2.2
  - numhask-space-0.3.0
  - numhask-prelude-0.3.2
  - numhask-0.3.1
  - perf-0.5.0.0
  - perf-analysis-0.2.0.0
  - numhask-array-0.4.0.0

allow-newer: true
