resolver: lts-14.13

packages:
  - .
  #- ../numhask-array
  #- ../numhask/numhask
  #- ../numhask/numhask-prelude

extra-deps:
  - rdtsc-1.3.0.1
  - readme-lhs-0.2.2
  - numhask-space-0.3.0
  - numhask-prelude-0.3.3
  - numhask-0.4.0
  - perf-0.5.0.0
  - perf-analysis-0.2.0.0
  - numhask-array-0.5.1

allow-newer: true
